# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/clion/112/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /snap/clion/112/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/oleg/Public/Oleg/course_2/ded/differentiator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/oleg/Public/Oleg/course_2/ded/differentiator

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/clion/112/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/snap/clion/112/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/oleg/Public/Oleg/course_2/ded/differentiator/CMakeFiles /home/oleg/Public/Oleg/course_2/ded/differentiator/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/oleg/Public/Oleg/course_2/ded/differentiator/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named diferentiator

# Build rule for target.
diferentiator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 diferentiator
.PHONY : diferentiator

# fast build rule for target.
diferentiator/fast:
	$(MAKE) -f CMakeFiles/diferentiator.dir/build.make CMakeFiles/diferentiator.dir/build
.PHONY : diferentiator/fast

containers/auto_free/auto_free.o: containers/auto_free/auto_free.cpp.o

.PHONY : containers/auto_free/auto_free.o

# target to build an object file
containers/auto_free/auto_free.cpp.o:
	$(MAKE) -f CMakeFiles/diferentiator.dir/build.make CMakeFiles/diferentiator.dir/containers/auto_free/auto_free.cpp.o
.PHONY : containers/auto_free/auto_free.cpp.o

containers/auto_free/auto_free.i: containers/auto_free/auto_free.cpp.i

.PHONY : containers/auto_free/auto_free.i

# target to preprocess a source file
containers/auto_free/auto_free.cpp.i:
	$(MAKE) -f CMakeFiles/diferentiator.dir/build.make CMakeFiles/diferentiator.dir/containers/auto_free/auto_free.cpp.i
.PHONY : containers/auto_free/auto_free.cpp.i

containers/auto_free/auto_free.s: containers/auto_free/auto_free.cpp.s

.PHONY : containers/auto_free/auto_free.s

# target to generate assembly for a file
containers/auto_free/auto_free.cpp.s:
	$(MAKE) -f CMakeFiles/diferentiator.dir/build.make CMakeFiles/diferentiator.dir/containers/auto_free/auto_free.cpp.s
.PHONY : containers/auto_free/auto_free.cpp.s

containers/Bor/Bor.o: containers/Bor/Bor.cpp.o

.PHONY : containers/Bor/Bor.o

# target to build an object file
containers/Bor/Bor.cpp.o:
	$(MAKE) -f CMakeFiles/diferentiator.dir/build.make CMakeFiles/diferentiator.dir/containers/Bor/Bor.cpp.o
.PHONY : containers/Bor/Bor.cpp.o

containers/Bor/Bor.i: containers/Bor/Bor.cpp.i

.PHONY : containers/Bor/Bor.i

# target to preprocess a source file
containers/Bor/Bor.cpp.i:
	$(MAKE) -f CMakeFiles/diferentiator.dir/build.make CMakeFiles/diferentiator.dir/containers/Bor/Bor.cpp.i
.PHONY : containers/Bor/Bor.cpp.i

containers/Bor/Bor.s: containers/Bor/Bor.cpp.s

.PHONY : containers/Bor/Bor.s

# target to generate assembly for a file
containers/Bor/Bor.cpp.s:
	$(MAKE) -f CMakeFiles/diferentiator.dir/build.make CMakeFiles/diferentiator.dir/containers/Bor/Bor.cpp.s
.PHONY : containers/Bor/Bor.cpp.s

containers/my_string/my_string.o: containers/my_string/my_string.cpp.o

.PHONY : containers/my_string/my_string.o

# target to build an object file
containers/my_string/my_string.cpp.o:
	$(MAKE) -f CMakeFiles/diferentiator.dir/build.make CMakeFiles/diferentiator.dir/containers/my_string/my_string.cpp.o
.PHONY : containers/my_string/my_string.cpp.o

containers/my_string/my_string.i: containers/my_string/my_string.cpp.i

.PHONY : containers/my_string/my_string.i

# target to preprocess a source file
containers/my_string/my_string.cpp.i:
	$(MAKE) -f CMakeFiles/diferentiator.dir/build.make CMakeFiles/diferentiator.dir/containers/my_string/my_string.cpp.i
.PHONY : containers/my_string/my_string.cpp.i

containers/my_string/my_string.s: containers/my_string/my_string.cpp.s

.PHONY : containers/my_string/my_string.s

# target to generate assembly for a file
containers/my_string/my_string.cpp.s:
	$(MAKE) -f CMakeFiles/diferentiator.dir/build.make CMakeFiles/diferentiator.dir/containers/my_string/my_string.cpp.s
.PHONY : containers/my_string/my_string.cpp.s

containers/my_vector/my_vector.o: containers/my_vector/my_vector.cpp.o

.PHONY : containers/my_vector/my_vector.o

# target to build an object file
containers/my_vector/my_vector.cpp.o:
	$(MAKE) -f CMakeFiles/diferentiator.dir/build.make CMakeFiles/diferentiator.dir/containers/my_vector/my_vector.cpp.o
.PHONY : containers/my_vector/my_vector.cpp.o

containers/my_vector/my_vector.i: containers/my_vector/my_vector.cpp.i

.PHONY : containers/my_vector/my_vector.i

# target to preprocess a source file
containers/my_vector/my_vector.cpp.i:
	$(MAKE) -f CMakeFiles/diferentiator.dir/build.make CMakeFiles/diferentiator.dir/containers/my_vector/my_vector.cpp.i
.PHONY : containers/my_vector/my_vector.cpp.i

containers/my_vector/my_vector.s: containers/my_vector/my_vector.cpp.s

.PHONY : containers/my_vector/my_vector.s

# target to generate assembly for a file
containers/my_vector/my_vector.cpp.s:
	$(MAKE) -f CMakeFiles/diferentiator.dir/build.make CMakeFiles/diferentiator.dir/containers/my_vector/my_vector.cpp.s
.PHONY : containers/my_vector/my_vector.cpp.s

differentiator_tree/expression_parser.o: differentiator_tree/expression_parser.cpp.o

.PHONY : differentiator_tree/expression_parser.o

# target to build an object file
differentiator_tree/expression_parser.cpp.o:
	$(MAKE) -f CMakeFiles/diferentiator.dir/build.make CMakeFiles/diferentiator.dir/differentiator_tree/expression_parser.cpp.o
.PHONY : differentiator_tree/expression_parser.cpp.o

differentiator_tree/expression_parser.i: differentiator_tree/expression_parser.cpp.i

.PHONY : differentiator_tree/expression_parser.i

# target to preprocess a source file
differentiator_tree/expression_parser.cpp.i:
	$(MAKE) -f CMakeFiles/diferentiator.dir/build.make CMakeFiles/diferentiator.dir/differentiator_tree/expression_parser.cpp.i
.PHONY : differentiator_tree/expression_parser.cpp.i

differentiator_tree/expression_parser.s: differentiator_tree/expression_parser.cpp.s

.PHONY : differentiator_tree/expression_parser.s

# target to generate assembly for a file
differentiator_tree/expression_parser.cpp.s:
	$(MAKE) -f CMakeFiles/diferentiator.dir/build.make CMakeFiles/diferentiator.dir/differentiator_tree/expression_parser.cpp.s
.PHONY : differentiator_tree/expression_parser.cpp.s

differentiator_tree/expression_tree.o: differentiator_tree/expression_tree.cpp.o

.PHONY : differentiator_tree/expression_tree.o

# target to build an object file
differentiator_tree/expression_tree.cpp.o:
	$(MAKE) -f CMakeFiles/diferentiator.dir/build.make CMakeFiles/diferentiator.dir/differentiator_tree/expression_tree.cpp.o
.PHONY : differentiator_tree/expression_tree.cpp.o

differentiator_tree/expression_tree.i: differentiator_tree/expression_tree.cpp.i

.PHONY : differentiator_tree/expression_tree.i

# target to preprocess a source file
differentiator_tree/expression_tree.cpp.i:
	$(MAKE) -f CMakeFiles/diferentiator.dir/build.make CMakeFiles/diferentiator.dir/differentiator_tree/expression_tree.cpp.i
.PHONY : differentiator_tree/expression_tree.cpp.i

differentiator_tree/expression_tree.s: differentiator_tree/expression_tree.cpp.s

.PHONY : differentiator_tree/expression_tree.s

# target to generate assembly for a file
differentiator_tree/expression_tree.cpp.s:
	$(MAKE) -f CMakeFiles/diferentiator.dir/build.make CMakeFiles/diferentiator.dir/differentiator_tree/expression_tree.cpp.s
.PHONY : differentiator_tree/expression_tree.cpp.s

differentiator_tree/tree_dfs.o: differentiator_tree/tree_dfs.cpp.o

.PHONY : differentiator_tree/tree_dfs.o

# target to build an object file
differentiator_tree/tree_dfs.cpp.o:
	$(MAKE) -f CMakeFiles/diferentiator.dir/build.make CMakeFiles/diferentiator.dir/differentiator_tree/tree_dfs.cpp.o
.PHONY : differentiator_tree/tree_dfs.cpp.o

differentiator_tree/tree_dfs.i: differentiator_tree/tree_dfs.cpp.i

.PHONY : differentiator_tree/tree_dfs.i

# target to preprocess a source file
differentiator_tree/tree_dfs.cpp.i:
	$(MAKE) -f CMakeFiles/diferentiator.dir/build.make CMakeFiles/diferentiator.dir/differentiator_tree/tree_dfs.cpp.i
.PHONY : differentiator_tree/tree_dfs.cpp.i

differentiator_tree/tree_dfs.s: differentiator_tree/tree_dfs.cpp.s

.PHONY : differentiator_tree/tree_dfs.s

# target to generate assembly for a file
differentiator_tree/tree_dfs.cpp.s:
	$(MAKE) -f CMakeFiles/diferentiator.dir/build.make CMakeFiles/diferentiator.dir/differentiator_tree/tree_dfs.cpp.s
.PHONY : differentiator_tree/tree_dfs.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/diferentiator.dir/build.make CMakeFiles/diferentiator.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/diferentiator.dir/build.make CMakeFiles/diferentiator.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/diferentiator.dir/build.make CMakeFiles/diferentiator.dir/main.cpp.s
.PHONY : main.cpp.s

work_with_file_functions/file_work_functions.o: work_with_file_functions/file_work_functions.cpp.o

.PHONY : work_with_file_functions/file_work_functions.o

# target to build an object file
work_with_file_functions/file_work_functions.cpp.o:
	$(MAKE) -f CMakeFiles/diferentiator.dir/build.make CMakeFiles/diferentiator.dir/work_with_file_functions/file_work_functions.cpp.o
.PHONY : work_with_file_functions/file_work_functions.cpp.o

work_with_file_functions/file_work_functions.i: work_with_file_functions/file_work_functions.cpp.i

.PHONY : work_with_file_functions/file_work_functions.i

# target to preprocess a source file
work_with_file_functions/file_work_functions.cpp.i:
	$(MAKE) -f CMakeFiles/diferentiator.dir/build.make CMakeFiles/diferentiator.dir/work_with_file_functions/file_work_functions.cpp.i
.PHONY : work_with_file_functions/file_work_functions.cpp.i

work_with_file_functions/file_work_functions.s: work_with_file_functions/file_work_functions.cpp.s

.PHONY : work_with_file_functions/file_work_functions.s

# target to generate assembly for a file
work_with_file_functions/file_work_functions.cpp.s:
	$(MAKE) -f CMakeFiles/diferentiator.dir/build.make CMakeFiles/diferentiator.dir/work_with_file_functions/file_work_functions.cpp.s
.PHONY : work_with_file_functions/file_work_functions.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... diferentiator"
	@echo "... containers/auto_free/auto_free.o"
	@echo "... containers/auto_free/auto_free.i"
	@echo "... containers/auto_free/auto_free.s"
	@echo "... containers/Bor/Bor.o"
	@echo "... containers/Bor/Bor.i"
	@echo "... containers/Bor/Bor.s"
	@echo "... containers/my_string/my_string.o"
	@echo "... containers/my_string/my_string.i"
	@echo "... containers/my_string/my_string.s"
	@echo "... containers/my_vector/my_vector.o"
	@echo "... containers/my_vector/my_vector.i"
	@echo "... containers/my_vector/my_vector.s"
	@echo "... differentiator_tree/expression_parser.o"
	@echo "... differentiator_tree/expression_parser.i"
	@echo "... differentiator_tree/expression_parser.s"
	@echo "... differentiator_tree/expression_tree.o"
	@echo "... differentiator_tree/expression_tree.i"
	@echo "... differentiator_tree/expression_tree.s"
	@echo "... differentiator_tree/tree_dfs.o"
	@echo "... differentiator_tree/tree_dfs.i"
	@echo "... differentiator_tree/tree_dfs.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... work_with_file_functions/file_work_functions.o"
	@echo "... work_with_file_functions/file_work_functions.i"
	@echo "... work_with_file_functions/file_work_functions.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

